# Generated by Django 3.0.7 on 2020-09-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20200505_1938"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post", options={"ordering": ["status", "-created_on"]},
        ),
    ]
