# Generated by Django 3.1.7 on 2021-03-22 14:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('newest', models.BooleanField(default=False, help_text='If you accept it, these fields will be treated as valid terms&conditions for acceptance by users. The previous will be in the DB but not valid anymore')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
