# Generated by Django 3.0.7 on 2020-09-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms_conditions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="termcondition",
            name="newest",
            field=models.BooleanField(default=False),
        ),
    ]
