# Generated by Django 3.0.7 on 2020-09-23 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms_conditions", "0002_termcondition_newest"),
    ]

    operations = [
        migrations.AddField(
            model_name="termcondition",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
