# Generated by Django 3.0.7 on 2020-09-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms_conditions", "0003_termcondition_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termcondition",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
