# Generated by Django 3.0.7 on 2020-09-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms_conditions", "0004_auto_20200923_1114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termcondition",
            name="newest",
            field=models.BooleanField(
                default=False,
                help_text="If you accept it, these fields will be treated as valid terms&conditions for acceptance by users. The previous will be in the DB but not valid anymore",
            ),
        ),
    ]
