# Generated by Django 3.0.7 on 2020-09-23 10:39

from django.db import migrations

import ckeditor_uploader.fields


class Migration(migrations.Migration):

    dependencies = [
        ("terms_conditions", "0005_auto_20200923_1233"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termcondition",
            name="terms",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
